examples/README.md, examples/blockStreaming_doubleBuffer.md, examples/blockStreaming_lineByLine.md, examples/streaming_api_basics.md
This PR add the following documents for examples/ directory
- `README.md` : Table of contents.
- `streaming_api_basics.md` : Brief description of LZ4 API sets and how Streaming API works.
- `blockStreaming_doubleBuffer.md` : Document for `blockStreaming_doubleBuffer.c`
- `blockStreaming_lineByLine.md` : Document for `blockStreaming_lineByLine.c`
=> Comment on example directory

programs/lz4io.c
Hi Yann Collet,
Recently, I found unused code in lz4io.c
Thanks,
=> Removed unused lines.

lib/lz4frame.c, lib/lz4frame_static.h
=> Revert "Add more descriptive frame errors"

lib/lz4frame.c, lib/lz4frame_static.h
This reverts commit 5a6652708439800e30d21e0cd24ed15cfb745a8b.
=> Revert "Revert "Add more descriptive frame errors""

lib/lz4.c
As discussed in https://github.com/Cyan4973/lz4/issues/126.
=> Improved implementation of wild copy

lib/lz4.c
I created this PR to see the results of CI builds.
=> Different approach to pointer arithmetics

lib/lz4.c
Reworked reading from before the malloc'd buffer into within-bound reading followed by a left shift (little-endian logic applies here).
Unfortunately, the performance of `MT_wildCopyNarrowLE` is halved when unaligned pointer ops are replaced with `memcpy`. More work should be applied to avoid `memcpy`.
=> Avoid out-of-bounds reading

lib/lz4.c, lib/lz4.h, programs/lz4cli.c
Resolve issue #192.
> *** LZ4 CLI 64-bits r132 (lib 1.7.2), by Yann Collet ***
=> lz4cli: print library version

README.md
Trivial fix.  But I've finally create PR in GitHub's online interface (i.e. without any text editor)!
=> Fix wrong link for Travis

cmake_unofficial/CMakeLists.txt
This performs the same substitutions as lib/Makefile.
=> cmake: Install liblz4.pc

lib/lz4.c
Check ALLOCATOR() failure and bail out, or it will crash.
=> Alloc failure fixes

Makefile, lib/Makefile, programs/Makefile
Add FreeBSD to install targets
=> Add FreeBSD to install targets

appveyor.yml, lib/lz4frame.h, programs/lz4cli.c, programs/lz4io.c, programs/lz4io.h, visual/VS2010/datagen/datagen.vcxproj, visual/VS2010/frametest/frametest.vcxproj, visual/VS2010/fullbench/fullbench.vcxproj, visual/VS2010/fuzzer/fuzzer.vcxproj, visual/VS2010/liblz4/liblz4.vcxproj, visual/VS2010/lz4/lz4.vcxproj
added --rm option
Copy owner, file permissions and modification time
fixed appveyor tests
=> added --rm option

contrib/gen_manual/Makefile, contrib/gen_manual/README.md, contrib/gen_manual/gen_manual.cpp, lib/README.md, programs/lz4io.c, programs/util.h
@inikep you intended to use the regular BSD license right?
=> Fix license and remove references to zstd

examples/frameCompress.c
=> Add frame decompression example

contrib/cmake_unofficial/CMakeLists.txt
=> cmake: make PIC configurable, add copyright and maintainer info

tests/Makefile
This is mentioned as an aside in @mwgamera's comment to #308, but isn't directly related to that bug.
=> Don't use "foo && false || true"

circle.yml, programs/Makefile, programs/bench.c, programs/lz4io.c, programs/platform.h, programs/util.h, tests/Makefile
fixed fseek with original MinGW (http://www.mingw.org/)
=> Circle CI tests

Makefile, contrib/gen_manual/.gitignore, contrib/gen_manual/Makefile, doc/lz4_manual.html, doc/lz4frame_manual.html, lib/Makefile, lib/lz4.h, lib/lz4frame.c, lib/lz4frame.h, lib/lz4frame_static.h, lib/lz4hc.c, programs/Makefile, tests/frametest.c
=> Reset decompression context

index.html
=> Apache Commons Compress supports LZ4 as of version 1.14

doc/lz4_Frame_format.md
* preview: https://github.com/Chocobo1/lz4/blob/1c9d4091dab0b27f63d067b6be5701afb9aba124/doc/lz4_Frame_format.md
* previous: https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md
=> [Doc] Fix markdown

doc/lz4_Frame_format.md, doc/lz4_manual.html, doc/lz4frame_manual.html, examples/frameCompress.c, lib/lz4.c, lib/lz4.h, lib/lz4frame.c, lib/lz4frame.h, lib/lz4frame_static.h, lib/lz4hc.c, lib/lz4hc.h, tests/frametest.c
Look into lib/lz4frame_static.h
=> Frame Dictionary API

INSTALL, Makefile, README.md, doc/lz4frame_manual.html, lib/Makefile, programs/Makefile, programs/lz4cli.c
supports lowercase directory variables 
add an "Installation" section in README.md 
added an INSTALL file
=> better respect GNU standard Makefile conventions

programs/Makefile
also : lz4c is now a symlink to lz4
=> fixed man directory installation (#387)

lib/lz4.c
This modification provides a 3-4% compression speed boost at all compression levels.
=> faster LZ4_count()

programs/lz4io.c, programs/util.h
=> [lz4io] Fix decompression file stat with --rm

lib/lz4.c
Or: `goto` Considered Harmful
Or: https://xkcd.com/292/
=> Return to Allowing Early Returns in LZ4_compress_generic()

lib/lz4.c
This actually ensures the guarantee referred to in the comment in
LZ4_compress_fast_continue().
=> Always Bump Offset by 64 KB in LZ4_loadDict()

lib/lz4frame.c
=> Limit Dictionary Size During LZ4F Decompression

Makefile, lib/Makefile, programs/Makefile, tests/Makefile
lz4 1.8.2 works fine on Haiku and passes all tests.
=> Add Haiku as a validated target.

lib/lz4.h
=> Fix LZ4_compress_fast_continue() docs

programs/lz4io.c
displayed at end of compression (see #555).
Also : adds a `cpu load = X%` indicator, by comparing wall time with execution time.
=> fixed compression time

NEWS, README.md, doc/lz4_manual.html, doc/lz4frame_manual.html, lib/lz4.h, programs/lz4.1, programs/lz4.1.md, programs/lz4cli.c, tests/.gitignore, tests/Makefile
following suggestion from @stbrumme (#558)
Also : bumped version number, regenerated man page and html doc
=> updated documentation for dictionary compression

lib/lz4.c
and separate it from `MATCH_SAFEGUARD_DISTANCE`.
While both constants have same value,
they do not serve same purpose, hence should not be confused.
=>  clarify constant MFLIMIT

lib/xxhash.c, lib/xxhash.h
This version has passed `cppcheck` static analyzer,
which I also plan to deploy for LZ4 CI tests.
=> updated xxhash to latest version

.travis.yml, Makefile, contrib/gen_manual/gen_manual.cpp, examples/blockStreaming_lineByLine.c, examples/compress_functions.c, examples/frameCompress.c, examples/simple_buffer.c, lib/lz4.c, lib/lz4frame.c, lib/lz4hc.c, programs/lz4cli.c, programs/lz4io.c, programs/util.h, tests/frametest.c, tests/fullbench.c
to travisCI,
and fixed a bunch of associated warnings.
=> Added cppcheck static analyzer test

lib/lz4.c, lib/lz4hc.c, tests/Makefile
Repro:
```
$ cat lz4hc.c >> lz4.c
$ cc -c lz4.c   # compile properly
```
=> Enable amalgamation of lz4hc.c and lz4.c

lib/Makefile, lib/README.md
This fixes cross compilation on linux for Windows
=> Add DLLTOOL variable so that one can override dlltool binary

lib/README.md, lib/lz4.c, lib/lz4frame.c, lib/lz4hc.c, tests/Makefile
Now support `lz4.c`, `lz4hc.c` and `lz4frame.c`
```
cat lz4.c > lz4_all.c
cat lz4hc.c >> lz4_all.c
cat lz4frame.c >> lz4_all.c
```
=> [amalgamation] lz4frame.c

.travis.yml, contrib/meson/GetLz4LibraryVersion.py, contrib/meson/InstallSymlink.py, contrib/meson/contrib/gen_manual/meson.build, contrib/meson/contrib/meson.build, contrib/meson/examples/meson.build, contrib/meson/lib/meson.build, contrib/meson/meson.build, contrib/meson/meson_options.txt, contrib/meson/programs/meson.build, contrib/meson/tests/meson.build
If you want to move this meson build changesets to under directory `contrib`. Just tell me.
But having meson in source tree help maintaining and using it more easier.
=> Support for Meson build and its CI tests

tests/fuzzer.c
the test fails, as intended,
since #631 is not merged yet in this branch.
=> add a test to check long sequences (#631)

lib/lz4hc.c
This PR adds a simple macro that makes the effectfulness to certain variables passed in to the `LZ4HC_encodeSequence` function clear. 
Runtime performance: ran tests on silesia corpus on my laptop and noticed no degradation in performance (and after macro expansion the code is identical).
=> Make effectfulness of calls to LZ4HC_encodeSequence clearer

.travis.yml
- Prefer `script` field than `Cmd` 
- Prefer `apt-get` in `install` field than `addons-apt-sources`
=> Travis: Clean up .travis.yml

contrib/meson/lib/meson.build, contrib/meson/meson.build
Thanks @nacho for pointing it out.
Equivalent to 
https://github.com/lz4/lz4/blob/6305e43dce0c8f0049167a41f92973fc1ef8a624/lib/Makefile#L106-L111
=> meson: Add -DLZ4_DLL_EXPORT=1 to build dynamic lib on Windows

lib/README.md, lib/lz4.c
and others minor comments / formats
while testing LZ4 for ARM
=> LZ4_FAST_DEC_LOOP macros

doc/lz4_manual.html, lib/lz4.h, lib/lz4frame.c, lib/lz4hc.h
=> moved _destSize() into "stable API" status

lib/lz4frame.c, lib/lz4frame.h, tests/frametest.c
=> made LZ4F_getHeaderSize() public

README.md, doc/lz4_manual.html, doc/lz4frame_manual.html, lib/lz4.h, lib/lz4frame.h, programs/README.md
Improved documentation of LZ4 dictionary compression
=> Dictionary compression

lib/lz4.c, lib/lz4frame.c, lib/lz4hc.c, programs/util.h, tests/fullbench.c, tests/fuzzer.c
fix #590 
I've seen only false positive so far.
Mostly to please Visual parser.
=> Fix some Visual conversion warnings

Makefile, lib/lz4frame.c, lib/lz4frame.h
=> lz4frame: initializers compatibility with C++

lib/lz4frame.h, programs/lz4.1.md, programs/lz4cli.c, programs/lz4io.c, programs/lz4io.h
=> Implement --list

lib/Makefile
=> lib/Makefile: Fix detection of `Darwin`.

lib/README.md, tests/Makefile
* test-amalgamation: fix the list of prerequisites
* test-amalgamation: use a single cat command
* test-amalgamation: fix compilation options
* test-amalgamation: split the rule
=> Fix test-amalgamation

.travis.yml, contrib/meson/meson.build
* Update ninja version to 1.9 in CI.
* Update default project version in meson script.
=> contrib: Make Meson build non optional

programs/lz4cli.c
=> fix #734 : --version should output to stdout

lib/lz4.c
The shortcut added in lz4-1.9.0 added an out-of-bounds read in the case where the match length is less than `ML_MASK` when we're not in ext-dict mode.
* Check the offset in the shortcut when we aren't in `withPrefix64k` mode.
* Always check the offset in the `safe_match_copy` label, even though it is already checked for longer matches.
Tested by running a fuzzer equivalent to the decompression fuzzer in https://github.com/lz4/lz4/pull/739. It crashed in ASAN mode in under 10 seconds with both bugs. After it doesn't crash in 10 minutes of running in ASAN, UBSAN, and MSAN mode.
That doesn't guarantee there aren't more bugs, but at least there aren't 10 second bugs.
@Cyan4973 is going to follow up and see why we didn't catch this bug with our own fuzzer tests, and AFL fuzz on the CLI.
Fixes …
=> Fix out-of-bounds read

tests/frametest.c, tests/fuzzer.c
with a capability to generate issue #738.
=> updated frametest

examples/simple_buffer.c
updates the sample input text to a more compressible one so compression wouldn't yield a larger output.
=> simple buffer example minor input update. fixes #750

lib/lz4hc.c
Fixes #761.
Tested by running the ossfuzz round trip fuzzers overnight without any errors (but they caught bugs during development and in the initial version quickly).
=> [LZ4HC] Speed up pattern compression with external dictionary
