lz4/lz4

lib/lz4.h
lib/lz4hc.h

Trivial fix. Since `DEPRECATED` is too generic name to public header, this PR replace the following macros:
- `_DEPRECATE_WARNING_DEFBLOCK` to `LZ4_DEPRECATE_WARNING_DEFBLOCK`
- `DEPRECATED` to `LZ4_DEPRECATED`

Add LZ4 prefix to deprecation macros

---

examples/blockStreaming_doubleBuffer.c
examples/blockStreaming_lineByLine.c

This trivial PR fix the following things
- Replace obsolete function `LZ4_compress_continue()` with recommended function `LZ4_compress_safe_continue()`
- Add `snprintf` macro for MSVC

Replace obsolete functions in example code

---

lib/lz4frame.c
lib/lz4frame_static.h

I was working on validating a different library's results and found this patch very helpful in pinpointing problems. Especially since not all implementations of lz4 support all features of lz4 frames.
Re-do of https://github.com/Cyan4973/lz4/pull/88 to hopefully go to the correct branch.

Add more descriptive frame errors

---

lib/lz4.c
lib/lz4.h
lib/lz4hc.h

This trivial PR fixes the following issues
- Replace `GCC_VERSION` macro in public header with `LZ4_GCC_VERSION`
- Since `GCC_VERSION` is common name, its name collision probability is quite high.
- Fix `LZ4_DEPRECATED` macro for old/non-gcc/clang/MSVC compilers
- Add placeholder argument

Fix LZ4_DEPRECATED() for old compilers

---

lib/lz4frame.h

Add LZ4F_OBSOLETE_ENUM() to describe obsolete enums
This PR improves PR #95
- Add LZ4F_OBSOLETE_ENUM() to describe obsolete enums
- Add compatible typedefs for obsolete enum types
- Remove constant macros
Remaining problem:
- [`LZ4F_LIST_ERRORS` in lz4frame_static.h](https://github.com/Cyan4973/lz4/blob/d153aaa1c236ba464beec4171d76063b5109b18c/lib/lz4frame_static.h#L49)
- Since it has special notation for error strings, I leave it for now.

Add LZ4F_OBSOLETE_ENUM() to describe obsolete enums

---

cmake_unofficial/CMakeLists.txt

The following changes allow for builds on AIX and HPUX
with the native (non-gcc) compilers, as well as
Visual Studio 2008 and Visual Studio 2012.
Also work around a build error with gcc on Solaris
which fails due to the system detecting an attempt
to use C99 mode with an XPG mode less than XPG6.

cmake support for AIX, HPUX, Solaris and Windows

---

cmake_unofficial/CMakeLists.txt

I believe the intention here was to also install lz4frame.h in the cmake file similarly to the Makefile-based build.

Install the lz4frame.h header in the cmake build

---

.travis.yml
Makefile
test/Makefile
test/test-lz4-versions.py

This PR resolves issue #103.
It adds compatibility test between all released (git tagged) versions of LZ4.
- Add Makefile target "[`versionstest`](https://github.com/Cyan4973/lz4/compare/dev...t-mat:issue/103pr2?expand=1#diff-b67911656ef5d18c4ae36cb6741b7965R117)".
- Standard test procedure like "`make versionstest && make clean`" works properly.
- Add `test` directory and its [Makefile](https://github.com/Cyan4973/lz4/compare/dev...t-mat:issue/103pr2?expand=1#diff-0d8f5a336dfc7f93d0f8ebb4026e4d46R1) and Python3 [script](https://github.com/Cyan4973/lz4/compare/dev...t-mat:issue/103pr2?expand=1#diff-90c37dff7749a6f2e2baa839336e439eR1).
- Add Travis build matrix entry [`env: LZ4_TRAVIS_CI_ENV=versionstest`](https://github.com/Cyan4973/lz4/compare/dev...t-mat:issue/103pr2?expand=1#diff-354f30 …

Add compatibility test between releases (resolves issue #103 )

---

test/test-lz4-versions.py

This PR is related to #104 and adds the following minor features :
- Add iterative edit and testing for frequent testing
- Add duplicated file recognition log
- Add SHA1 of unique .lz4 file to the log

Add supporting iterative edit and testing to versionstest

---

.dir-locals.el
programs/lz4cli.c

I must have spent ten minutes trying to get the "lz4" tool to work before realizing that "Incorrect parameters" meant "you're writing to a pty".

Improve lz4 command line error message when dealing with console IO

---

cmake_unofficial/CMakeLists.txt

left static-only targets for windows for now, as adding dynamic libraries would require to build a symbol definition file etc

added static build target for OSX and Linux to cmake

---

visual/2012/lz4.sln
visual/2012/lz4/liblz4.vcxproj
visual/2012/lz4/liblz4.vcxproj.filters

This replaces PR #146. Note that static library targets can also be built via CMake, if available (see PR #172)

Add static library target for msbuild

---

programs/lz4io.c

Header file name is case insensitive on Windows but it is case sensitive
on Linux. "Windows.h" can't be found on Linux.

Fix build error on MinGW

---

programs/Makefile

If the $(EXT) are added, "make install" can work with MinGW build on
Linux.

Add missing $(EXT)

---

examples/Makefile
lib/liblz4.pc.in
lib/lz4.c
lib/xxhash.c
versionsTest/test-lz4-versions.py

I noticed that a few `http://...` links could be replaced by `https://...` links, which are usually deemed "safer".  Also, the self-reference is broken, as it still points to a googlecode repository.  This raises a few warnings when used downs stream ([example](https://github.com/tgingold/ghdl/pull/117)).

Clean up links, repository-wide

---

programs/lz4io.c

Linux uses case sensitive file system. So "Windows.h" doesn't exist.
% make CC=x86_64-w64-mingw32-gcc EXT=.exe SHARD_EXT=dll
...
lz4io.c:69:73: fatal error: Windows.h: No such file or directory
compilation terminated.
...

Fix build error with MinGW on Linux

---

cmake_unofficial/CMakeLists.txt
examples/Makefile
lib/Makefile
programs/lz4cli.c

Main changes:
- request POSIX.2001 definitions in a portable fashion
- fix compile on Solaris 10
- cmake build file fixes
cf. the commit messages for details

Fix POSIX portability and cmake file

---

programs/lz4io.c

"WinIoCtl.h" works on Windows because Windows uses case insensitive file
system. But it doesn't work on GNU/Linux (for cross compiling with
MinGW) because GNU/Linux uses case sensitive file system.

Use lower case for header file name

---

lib/Makefile
lib/lz4.h
lib/lz4frame.h
lib/lz4hc.h
programs/Makefile
visual/VS2010/datagen/datagen.vcxproj
visual/VS2010/frametest/frametest.vcxproj
visual/VS2010/fullbench/fullbench.vcxproj
visual/VS2010/fuzzer/fuzzer.vcxproj
visual/VS2010/liblz4/liblz4.vcxproj
visual/VS2010/lz4/lz4.vcxproj

It's based on Zstandard's ZSTDLIB_API.
See also: https://github.com/Cyan4973/lz4/issues/216#issuecomment-226245432
Deprecated functions aren't LZ4LIB_API targets. Because we don't need to
export deprecated functions from now.
There are same LZ4LIB_API definitions in each header files instead of
including a common header file because LZ4_DEPRECATED is defined so.

Add LZ4LIB_API

---

programs/lz4cli.c
programs/lz4io.c
programs/lz4io.h
tests/Makefile

Fix test mode to not always return success.
Don't ask for permission to overwrite `nulmark`.
Another option, `g_passThrough` is necessary because if the user passes `-t`, we shouldn't silently ignore errors, even if `-f` is passed as well.  Thanks to @t-mat for this part of the patch.
Fixes #199 
Before:
> echo "hello world" > file
> lz4 -t file
successfully decoded 12 bytes
> lz4 -tf file
successfully decoded 12 bytes
> lz4 file null
Warning : /dev/null already exists
Overwrite ? (Y/n) : n
Error 12 : No. Operation aborted : /dev/null already exists
> lz4 file /dev/null
Warning : /dev/null already exists
Overwrite ? (Y/n) : n
Error 12 : No. Operation aborted : /dev/null already exists
After:
> lz4 -t file
Error 44 : Unrecognized header : file cannot be decoded
> lz4 -tf file
Error 44 : …

Fix test mode and write to null

---

lib/lz4.c
programs/lz4.1
programs/lz4cli.c
tests/Makefile

Make `lz4 file-does-not-exist` return non-zero.
Fixes #177 
Fixes #167

Return error if input file does not exist.

---

lib/lz4.c
tests/Makefile
tests/fasttest.c

It specified the external dictionary location incorrectly.
Add tests that expose this bug with both normal compilation and ASAN.
Fixes #166

Fix LZ4_decompress_fast_continue() bug

---

contrib/cmake_unofficial/CMakeLists.txt

This makes it much easier to include LZ4 in a CMake-based project;
you only need to add_subdirectory(lz4/contrib/cmake_unofficial),
then you can use the lz4 target (which is the library).  In bundled
mode a static library will be built and nothing will be installed,
although the lz4 and lz4c command line tools will still be built.
This also makes some other much less intrusive changes, including:
* Version information is now parsed from lib/lz4.h so the
CMakeLists.txt file no longer needs to manually be kept up to date
manually.
* pkg-config file uses ${prefix} where appropriate instead of writing
out full paths, which is important for people on Windows.
* Warning flags are now checked instead of blindly added.
* The GNUInstallDirs module is used to determine installation
locations.
* The …

cmake: significant changes to accomodate a new "bundled" mode.

---

examples/.gitignore
examples/Makefile
examples/README.md
examples/dictionaryRandomAccess.c
examples/dictionaryRandomAccess.md

Add an example that shows how to use an external dictionary.
It also shows a simple example of a jump table for random access.
Also switch `frameCompress` to use `liblz4.a`, since it was broken when I tried to run `make -C examples test`.
Closes #187

Add dictionary random access example

---

doc/lz4_manual.html
lib/lz4.c
lib/lz4.h
lib/lz4hc.c
lib/lz4hc.h

Expose internal types inside a union to remove strict aliasing.  There is no ABI or API breakage because the external struct has exactly the same type, size, and alignment.

Expose internal types to remove strict aliasing

---

programs/Makefile
programs/lz4.1.md

Yay!  I finally make free time.  So I did trivial thing.
- `make man` makes manpage `lz4.1` from `lz4.1.md`
- It needs `ruby`, `gem` and `ronn`.  These are same as xxhash is required.
Open problems are
- `LIBVER_*` variables in the `Makefile` are duplicated.  It may harm future maintainability.
- Since `ronn` is no longer maintained, same kind of another tool such as `md2man` may be better choice.  But I use `ronn` for now.
- It would be nice if we output HTML manpage for lz4.org

Add "man" target to Makefile

---

programs/bench.c
programs/lz4cli.c

Those warnings are found by cppcheck...

Fix warnings

---

contrib/cmake_unofficial/CMakeLists.txt

Otherwise the version in .pc file is empty.
Bug: https://bugs.gentoo.org/608144

[cmake] Fix substituting version in liblz4.pc

---

lib/Makefile

This is needed on systems where it isn't the parent of
$(PKGCONFIGDIR), and so doesn't get created implicitly.

Explicitly create $(DESTDIR)$(LIBDIR)/ at install time

---

tests/Makefile

When no output filename is specified and stdout is not a terminal,
lz4 doesn't attempt to guess an output filename and uses stdout for
output.
This change fixes test-lz4-basic when run without a terminal
by specifying output filenames.

Fix test-lz4-basic

---

lib/Makefile
lib/lz4.h
lib/lz4frame.h

Windows builds already limit exporting of functions to those marked with LZ4LIB_API tag.
This short series implements the same behavior on other platforms assuming that gcc >= 4 (released ~12 years ago) is used.

Export only those symbols that are part of public API

---

NEWS
programs/lz4.1.md
programs/lz4cli.c
tests/Makefile

This option is supported by other compressors with compatible cli,
so add it to lz4 as well for better compatibility.

cli: add GNU separator -- specifying that all following arguments are files

---

lib/lz4hc.h

Commit 25b243588585b06a2d947372284cbfe00da930e9 exported deprecated
symbols declared in lz4.h by marking all LZ4_DEPRECATED functions with
LZ4LIB_API attribute.  This change does the same with functions declared
in lz4hc.h file, thus extending the export to lz4hc.h.
As result, the following 17 deprecated functions are exported again:
LZ4_compressHC
LZ4_compressHC2
LZ4_compressHC2_continue
LZ4_compressHC2_limitedOutput
LZ4_compressHC2_limitedOutput_continue
LZ4_compressHC2_limitedOutput_withStateHC
LZ4_compressHC2_withStateHC
LZ4_compressHC_continue
LZ4_compressHC_limitedOutput
LZ4_compressHC_limitedOutput_continue
LZ4_compressHC_limitedOutput_withStateHC
LZ4_compressHC_withStateHC
LZ4_createHC
LZ4_freeHC
LZ4_resetStreamStateHC
LZ4_sizeofStreamStateHC
LZ4_slideInputBufferHC

Export deprecated symbols declared in lz4hc.h

---

programs/lz4cli.c

Add some extra logic so that `./lzcat` matches, `lzcat.exe` matches, but `lzcatsss` doesn't.
Fixes #335

Ignore extensions in exe name matching

---

programs/platform.h

Fixes https://github.com/lz4/lz4/issues/336 with slight modification to the patch, as it didn't build on MSVC.
Tested that CYGWIN doesn't need the patch (it doesn't seem to have `NUL` anyway)

Fix IS_CONSOLE returning 1 for NUL on windows

---

lib/lz4frame.c
lib/lz4hc.c
programs/lz4cli.c

For the default Wimplicit-fallthrough=3 level,
the comment should start with "fall*"
~~About the fix in lz4cli.c, `gcc 7.1.1` will only suppress the warning when done like this:~~
```c++
#ifdef UTIL_HAS_CREATEFILELIST
/* recursive */
case 'r': recursive=1;  /* without break */
#endif
/* fall-through */
```
~~so I opt to use `__attribute__ ((fallthrough));` which can be placed in the `#ifdef` block~~

Fix gcc7 Wimplicit-fallthrough warnings

---

tests/Makefile

LIBDIR may be overriden with a environment variable: In this case make
clean breaks in tests/. Use another variable name.

tests/Makefile: don't use LIBDIR as variable

---

programs/lz4.1.md

The "Concatenation of .lz4 files" section contains example commands
that are run together on one line, making them invalid. Wrap them
in a code block and clean up surrounding formatting.

Fix formatting of concatenation example

---

programs/lz4.1

I realized that, since `lz4.1` _is_ present in to the source tree, it probably made sense to check in an updated version. This is the result of running `make man` in the `programs/` directory, and incorporates all of the changes to `lz4.1.md` since the file was last generated (not just my recent edit).

Generate updated man page from Markdown source

---

lib/Makefile

This resolves an issue whereby `make install` would not install `liblz4.a`, and also adds `lz4frame_static.h` to be installed if BUILD_STATIC==yes.

Fix typos preventing installation of static lib.

---

lib/lz4.c
lib/xxhash.c

FORCE_INLINE macro is defined based on the compiler used. When using
gcc, it will include "__attribute__((always_inline))" forcing gcc to
always inline all the functions marked as FORCE_INLINE. However, this
can cause a performance degradation of about 15%.
This patch allows to set the FORCE_INLINE macro from the compiler
command line to either "static" or "static inline" giving allowing it
to inline functions as needed when performing optimizations.

Allow to predefine FORCE_INLINE macro.

---

NEWS
doc/lz4frame_manual.html
examples/frameCompress.c
lib/lz4frame.c
lib/lz4frame.h
lib/lz4frame_static.h
programs/lz4cli.c
programs/lz4io.c
tests/Makefile
tests/frametest.c

lz4frame now supports block checksum, as defined in the specification.
Restored block checksum command (`-BX`) on CLI

Block checksum

---

examples/frameCompress.c

The build in the OpenBSD ports tree on the armv7 platform fails because the main function of the frameCompress example is missing the final return statement. Output was:
```./frameCompress Makefile
inp = [Makefile]
lz4 = [Makefile.lz4]
dec = [Makefile.lz4.dec]
compress : Makefile -> Makefile.lz4
Buffer size is 262175 bytes, header size 7 bytes
Writing 1831 bytes
Makefile: 3276 → 1831 bytes, 55.9%
compress : done
decompress : Makefile.lz4 -> Makefile.lz4.dec
Writing 3276 bytes
decompress : done
verify : Makefile <-> Makefile.lz4.dec
verify : OK
gmake[1]: *** [Makefile:89: test] Error 40
gmake[1]: Leaving directory '/usr/ports/pobj/lz4-1.8.0/lz4-1.8.0/examples'
gmake: *** [Makefile:73: examples] Error 2
```

Fix: Add return statement to main function

---

lib/lz4.h

Clang doesn't accept a C++11 attribute following `LZ4LIB_API`.
Use the GNU attribute instead.

Don't use C++11 deprecation attribute with clang

---

lib/lz4frame.c

With my forthcoming changes to support using dictionaries from the command line, it's possible to induce a segfault at lz4frame.c:1642 (`memcpy(dctx->tmpOutBuffer, oldDictEnd - newDictSize, newDictSize);`). This is because when reading from a file, the first call to `LZ4F_decompress` is with just the magic number. `dstage_init` isn't reached in that call, so `dctx->tmpOutBuffer` isn't allocated.

Fix dict segfault

---

lib/lz4.c

This PR is to propose using the optimization level of O2, instead of O3, for the decompression functions in lz4.c on ppc64le with gcc.
>  Gcc on ppc64le generates an unrolled SIMDized loop for LZ4_wildCopy,
>  together with a simple 8-byte copy loop as a fall-back path.
>  However, this optimization hurts the decompression speed by >30%,
>  because the execution does not go to the optimized loop
>  for typical compressible data, and all of the preamble checks
>  before going to the fall-back path become useless overhead.
>  This optimization happens only with the -O3 flag, and -O2 generates
>  a simple 8-byte copy loop.
>  With gcc on ppc64le, all of the LZ4_decompress_* and LZ4_wildCopy
>  functions are annotated with __attribute__((optimize("O2"))),
>  and also LZ4_wildCopy is forcibly …

Use O2 for the decompression functions on ppc64le with gcc

---

lib/lz4.h

To allow user to redefine symbols visibility, I have separated visibility part from LZ4LIB_API macro and created another LZ4LIB_VISIBILITY macro. This new LZ4LIB_VISIBILITY macro can be redefined during compilation. 
Inspired by zstd project, header zstd.h, macro ZSTDLIB_API.

Separated visibility from LZ4LIB_API macro.

---

programs/bench.c
programs/util.h

The timer used was only accurate up to 0.01 seconds. This timer is accurate up to 1 ns.
It is a monotonic timer that measures the real time difference, not on CPU time.
Copied the benchmark code from https://github.com/facebook/zstd/commit/6ab4d5e9041aba962a810ffee191f95897c6208e
CC @felixhandte

[bench] Use higher resolution timer on POSIX

---

lib/lz4.c

This modification improves decoding speed by 0-10%, depending on source file.
It was successfully tested on x64 and x86 (32-bits).
I haven't been able to test it on other architectures yet.

Faster decoding xp

---

lib/lz4.c

For example, with clang:
```
lz4.c:XXX:36: error: 'register' storage class specifier is deprecated and incompatible with C++17 [-Werror,-Wdeprecated-register]
static unsigned LZ4_NbCommonBytes (register reg_t val)
^~~~~~~~~
```

When building with a C++ compiler, remove the 'register' keyword to silent a warning

---

lib/README.md
lib/lz4.c
lib/lz4frame.c
lib/lz4hc.c
lib/lz4hc.h
lib/lz4opt.h
tests/fuzzer.c

The match finder has been changed from binary tree to hash train, requiring a full rewrite of optimal parser. The outcome is a seamless transition between regular HC parser and the new optimal parser.
It saves a bunch of incompatibility issues (`cdict`, `_destSize`), also unlocking ability to change compression level on the fly between blocks.
New optimal parser is faster and compress a little better than v1.8.0.
It also fixes #339.
See https://phabricator.intern.facebook.com/P58578327 for details.

Improve Optimal parser

---

programs/lz4io.c

LZ4IO_compressFilename_extRess does not check if dstFileName is /dev/null (nulmark) before calling UTIL_setFileStat on it, which can result in /dev/null being chmodded 644, 600, etc when it's the output file and lz4 is running as root. Fixed that here

Fix cli sometimes calling UTIL_setFileStat on /dev/null

---

appveyor.yml
visual/VS2010/datagen/datagen.vcxproj
visual/VS2010/frametest/frametest.vcxproj
visual/VS2010/fullbench-dll/fullbench-dll.vcxproj
visual/VS2010/fullbench/fullbench.vcxproj
visual/VS2010/fuzzer/fuzzer.vcxproj
visual/VS2010/liblz4-dll/liblz4-dll.vcxproj
visual/VS2010/liblz4/liblz4.vcxproj
visual/VS2010/lz4/lz4.vcxproj

PR to extend VS2010 project files with msbuild properties according to request [#423](https://github.com/lz4/lz4/issues/423)
1. WholeProgramOptimization is turned off by default and can be turned on (required for VS2010 builds) by providing additional property into msbuild command line
```
/p:WholeProgramOptimization=true
```
2. Custom msbuild property to specify type of msvc crt to be linked with ( [official docs](https://msdn.microsoft.com/en-us/library/2kzt1wy3.aspx) )
Statically linked msvc runtime:
```
/:RuntimeLibrary=MultiThreaded
```
Statically linked msvc runtime debug version:
```
/:RuntimeLibrary=MultiThreadedDebug
```
Dynamic linkage with msvc runtime is default options in VS.

Msbuild properties #423

---

lib/lz4.c

remove `register` keyword

---

lib/lz4hc.c
lib/lz4hc.h

lz4opt is competitive vs lz4hc level 10.
Below that level, it doesn't match the speed / compression effectiveness of regular hc parser.
This patch propose to extend lz4opt to levels 10-12.
The new level 10 tend to compress a bit better and a bit faster than previous one (mileage vary depending on file)
The only downside is that `limitedDestSize` mode is now limited to max level 9 (vs 10),
since it's only compatible with regular HC parser.
(Note : I suspect it's possible to convert lz4opt to support it too, but haven't spent time into it).

new level 10

---

programs/lz4.1.md

`lz4 -q input.tar` creates a `input.tar.lz4` as expected.
`nohup lz4 -q input.tar` creates a `nohup.out` file containing the binary output of the command.
`nohup lz4 -q input.tar input.tar.lz4` creates the `input.tar.lz4` file and an empty `nohup.out` file, as expected.
This behavior is documented in the man page: "When no destination name is provided, if stdout is not the console, it becomes the output (like a silent -c)", but it's surprising enough for a user who didn't read the man page to warrant describing it explicitly.

Docs: describe behavior under nohup

---

lib/lz4hc.c
lib/lz4opt.h

Pattern analysis (currently limited to long ranges of identical bytes)
can be detrimental to performance
when `nbSearches` is low.
Reason is : `nbSearches` provides a built-in protection for these cases.
The problem with patterns is that they dramatically increase the number of candidates to visit.
But with a low `nbSearches`, the match finder just aborts early.
In such cases, pattern analysis adds some complexity without reducing total nb of candidates.
It actually increases compression ratio a little bit, by filtering only "good" candidates,
but at a measurable speed cost, so it's not a good trade-off.
This patch makes pattern analysis optional.
It's enabled for levels 8+ only.

conditional pattern analysis

---

lib/lz4frame_static.h

In some contexts, *cough*like at facebook*cough*, dynamic linking is used in
contexts which aren't truly dynamic. That is, the guarantee is maintained that
a program will only ever execute against the library version it was compiled
to interact with.
For those situations, introduce a compile-time flag that overrides hiding
these unstable APIs in shared objects.

Add Option to Make lz4frame_static.h Functions Visible in Shared Objects

---

lib/lz4frame.c

[lz4f] Skip memcpy() on empty dictionary

---

lib/lz4.h

- Replace U+00A0 by space
- Fix build failure of archivers/py-borgbackup in FreeBSD
Reference: https://bugs.FreeBSD.org/225235

Change file format back to ASCII (from UTF-8)

---

lib/lz4hc.c

This changes the behavior back to match `lz4-1.8.0` and before.

[lz4hc] level == 0 means default, not level 1

---

lib/lz4.h
lib/lz4hc.h

When using clang++ with std c++14 or c++17 you would get the error "an attribute list cannot appear here" when including "lz4.h" as the visibility attribute is before the c++ attribute.
This ensures that the `[[deprecated]]` c++ attribute is before everything
else in the function declarations.
This also fixes https://github.com/lz4/lz4/issues/436

Ensure LZ4_DEPRECATED("...") is before LZ4LIB_API

---

doc/lz4_Frame_format.md

add new terms "LZ4 Frame Header" and "LZ4 Frame Footer"
as suggested by @psteinb in #445 and #457

Minor change to LZ4 Frame format specification

---

lib/lz4.c
lib/xxhash.c

On Windows, the Intel compiler is closer to MSVC rather than GCC and
does not support the GCC attribute syntax.
Fixes #468 
---
Includes the change from Cyan4973/xxHash#123.

intel: do not use __attribute__((packed)) on Windows

---

lib/lz4.c

gains about 1-2 % speed,
just by making the "shortcut" sequence more common.

Faster decoding speed

---

lib/lz4hc.c

These little changes speed up a bit Hash Chain match finder.
On my laptop, using `clang`: 
before : 
```
3#silesia.tar       : 211984896 ->  81347969 (2.606),  71.8 MB/s ,2356.7 MB/s
9#silesia.tar       : 211984896 ->  77890594 (2.722),  24.4 MB/s ,2420.0 MB/s
```
after : 
```
3#silesia.tar       : 211984896 ->  81347969 (2.606),  74.4 MB/s ,2351.9 MB/s
9#silesia.tar       : 211984896 ->  77890594 (2.722),  25.4 MB/s ,2371.1 MB/s
```

Faster HC 

---

programs/bench.c
programs/util.h

`time()` invocation is not free,
and when a unit of work is very small (like compressing / decompressing a small file)
`time()` invocation can actually represent a sizable fraction of workload measured.
The new strategy is to use `time()` only once per batch,
and dynamically resize batch size so that each round lasts approximately 1 second,
starting from a conservative (low) estimate.
This change only matters for small inputs.
Measurement for large files (such as silesia.tar) are much less impacted.
(though decoding speed is so fast that even medium-size files will notice an improvement).

Better bench measurements for small inputs

---

lib/lz4.c
lib/lz4hc.c
lib/lz4opt.h

The LZ4 block format specification
states that the last match must start
at a minimum distance of 12 bytes from the end of the block.
However, out of an abundance of caution,
the reference implementation would actually stop searching matches
at 13 bytes from the end of the block.
This patch fixes this small detail.
The new version is now able to properly compress a limit case
such as `aaaaaaaabaaa\n`
as reported by Gao Xiang (@hsiangkao).
Obviously, it doesn't change a lot of things.
This is just one additional match candidate per block.
With default policy, blocks are 4 MB long, so it doesn't happen too often
Compressing `silesia.tar` at default level 1 saves 5 bytes (100930101 -> 100930096).
At max level 12, it saves a grand 16 bytes (77389871 -> 77389855).
The impact is a bit more …

edge case fix : compress up to end-mflimit (12 bytes)

---

Makefile
tests/Makefile

according to GNU Makefile conventions,
the Makefile should feature a `make check` target
to self-test the generated program:
https://www.gnu.org/prep/standards/html_node/Standard-Targets.html .
this is much less thorough and less taxing than `make test`,
and can be run on any target in a reasonable timeframe (several seconds).

added target make check

---

tests/Makefile

When run with `-jN`, the `rm tmp*` can run in the middle of the `test-lz4-dict`
job, which will then fail, finding its files to have been axed. This adds a
dependency between the two.

Add Dependency to Fix Parallel `make test` Runs

---

programs/lz4io.c

wrong comparison, which was always overflowing (hence was always true)
except when it was not (i386, reported by pmc)
in which case it would never show any information.

fixed DISPLAYUPDATE()

---

lib/lz4.c
lib/lz4.h
lib/lz4frame.c

This Pull Request encompasses several related changes:
- More context preparation is concentrated in `LZ4_prepareTable()`, and it's callers change to only calling it when starting a new / independent compression stream.
- The functionality of `LZ4_prepareTable()` is exposed to external callers via a new function, `LZ4_resetStream_fast()`.
- `LZ4_compress_fast_extState_noReset()` is renamed `LZ4_compress_fast_extState_fastReset()` to reflect the fact that it calls `LZ4_resetStream_fast()` internally.
- `dictCtx` mode is made accessible via a new experimental API, `LZ4_attach_dictionary()`.
- The `LZ4_STATIC_LINKING_ONLY` macro is introduced to prevent dynamic linking against unstable APIs.
- LZ4F is modified to use these new APIs.
- Comments are improved.

Several Changes Concerning Table Preparation in LZ4 Fast

---

lib/lz4.c

It prevent redefine error when project which uses lz4 has its own likely/unlikely
macroses.

Wrap likely/unlikely macroses with #ifndef

---

lib/lz4.h

The notes about "security guarantee" and "malicious inputs" seemed
a bit non-technical to me, so I took the liberty to tone them down
and instead describe the actual risks in technical terms.  Namely,
the function never writes past the end of the output buffer, so
a direct hostile takeover (resulting in arbitrary code execution
soon after the return from the function) is not possible.  However,
the application can crash because of reads from unmapped pages.
I also took the liberty to describe what I believe is the only sensible
usage scenario for the function: "This function is only usable if the
originalSize of uncompressed data is known in advance," etc.

lz4.h: clarify the risks of using LZ4_decompress_fast()

---

lib/lz4.c
tests/fuzzer.c

The bug is a read up to 2 bytes past the end of the buffer.
There are three cases for this bug, one for each test case added.
* An empty input causes `token = *ip++` to read one byte too far.
* A one byte input with `(token >> ML_BITS) == RUN_MASK` causes
one extra byte to be read without validation. This could be
combined with the first bug to cause 2 extra bytes to be read.
* The case pointed out in issue #508, where `ip == iend` at the
beginning of the loop after taking the shortcut.
Benchmarks show no regressions on clang or gcc-7 on both my mac
and devserver.
Fixes #508.

Fix input size validation edge cases

---

lib/lz4.c

I had the displeasure to notice that, after update related to support of low memory addresses,
speed of lz4_fast on `clang` was reduced by 10% (note: there is no such impact with `gcc`).
The reason is this trivial change, from
`matchIndex+MAX_DISTANCE < current`
towards
`current - matchIndex > MAX_DISTANCE`
The second version is more robust, as it also survives a situation where `matchIndex > current` due to overflows. So it should be preferable.
However, the speed impact is massive, and cannot be ignored.
To work properly, the first version requires `matchIndex` to not overflow. Hence were added `assert()` conditions.
The only situation where `matchIndex` can overflow is with dictCtx compression,
when the dictionary context is not initialized before loading the dictionary.
Therefore, …

fixed lz4_fast clang performance

---

lib/Makefile

Just like BUILD_STATIC=no disables static libraries, BUILD_SHARED=no
disabled shared libraries. This is useful to support toolchains that do
not support shared libraries.

lib: allow to disable shared libraries

---

lib/Makefile
lib/lz4.c
programs/util.h
tests/Makefile

by disabling the shortcut, which it cannot use anyway
(see #506 )

Fixed performance issue with LZ4_decompress_fast()

---

lib/lz4frame.c
lib/lz4frame.h
lib/lz4frame_static.h
programs/lz4io.c
tests/frametest.c

This PR moves all of the declarations in `lz4frame_static.h` into `lz4frame.h`, protected by a macro, `LZ4F_STATIC_LINKING_ONLY`. This brings LZ4F into using the same pattern as LZ4 and Zstd. This diff safely preserves functionality for existing includes of `lz4frame_static.h` and in general should be safe for multiple inclusion with and without the guard macro defined.

Integrate Contents of `lz4frame_static.h` into `lz4frame.h`

---

doc/lz4_Block_format.md

[ Yann: If you further edit the spec, as I suggest with the TODO mark,
please also change the "Last revised" date. ]
It occurred to me that the formula "The last 5 bytes are always
literals", on the list of "assumptions made by the decoder", is
remarkably ambiguous.  Suppose the decoder is presented with 5 bytes.
Are they literals?  It may seem that the decoder degenerates
to memcpy on short inputs.  But of course the answer is no,
so the formula needs some clarification.
Parsing restrictions should be explained as well, otherwise they look
like arbitrary numbers.  The 5-byte restriction has been mentioned
recently in connection with the shortcut in LZ4_decompress_generic,
so I add that.  The second restriction is left to be explained
by the author.
I also took the liberty to explain that …

lz4_Block_format.md: clarify on short inputs and restrictions

---

lib/lz4.c
tests/fullbench.c
tests/fuzzer.c

I noticed that LZ4_decompress_generic is sometimes instantiated with
identical set of parameters, or (what's worse) with a subtly different
sets of parameters.  For example, LZ4_decompress_fast_withPrefix64k is
instantiated as follows:
return LZ4_decompress_generic(source, dest, 0, originalSize, endOnOutputSize,
full, 0, withPrefix64k, (BYTE*)dest - 64 KB, NULL, 64 KB);
while the equivalent withPrefix64k call in LZ4_decompress_usingDict_generic
passes 0 for the last argument instead of 64 KB.  It turns out that there
is no difference in this case: if you change 64 KB to 0 KB in
LZ4_decompress_fast_withPrefix64k, you get the same binary code.
Moreover, because it's been clarified that LZ4_decompress_fast doesn't
check match offsets, it is now obvious that both of these fast/withPrefix64k …

lz4.c: refactor the decoding routines

---

lib/Makefile

`make V=1` will now show the commands executed to build the library.
A similar technique is used in e.g. linux/Makefile.
The bulk of this change is produced with the following vim command:
:g!/^\t@echo\>/s/^\t@/\t\$(Q)/

lib/Makefile: show commands with V=1

---

lib/lz4hc.c

fix #230.
This is a non-trivial bug,
related to the way chain table is updated at end of block, in `_continue()` mode.
Depending on ptr address overflow, it could accidentally trigger partial update skip, 
hence different evolution of the chain table,
hence different compressed file.
Compressed files were always valid.
It's just they missed a few opportunities, and the missed part was basically random.
Skipped sections are generally quite small, and far apart,
so the impact to compression was very small (a few bytes on files > 100 MB).
Still, this patch fixes it, now producing always same compressed file, even on CentOS6.

fix lz4hc -BD non-determinism

---

NEWS
README.md
doc/lz4_manual.html
lib/lz4frame.c
tests/fuzzer.c

the initial intention was to update lz4f ring buffer strategy,
but lz4f doesn't use ring buffer ... 😛 
Instead, lz4f uses destination buffer as much as possible,
and copies just what's required to preserve history
into its own buffer, at the end.
Therefore, this patch merely clarifies a few comments and add some `assert()`.
It's built on top of #528.

Random lz4f clarifications

---

lib/lz4.h
lib/lz4frame.c

`LZ4_resetStream_fast()` will do a full reset if the table isn't in `byU32` mode, since it's built to prep the stream for streaming compression, i.e., `LZ4_compress_fast_continue()`. This can lead to unnecessary resets, such as when the stream is in `byU16` mode and will next be used in `byU16`, which can happen when performing sequential, independent, small compressions and which shouldn't require a reset.
This PR also clarifies some comments to be more explicit about how fastResets work.

LZ4F: Only Reset the LZ4_stream_t when Init'ing a Streaming Block

---

lib/lz4.c
lib/lz4frame.c
tests/frametest.c

It's a long-standing error, that can be reproduced reliably using following command :
`./frametest -v -i100000000 -s1659 -t31096808`
It's actually a bug in the streaming LZ4 API,
triggered by following scenario : 
start a new stream,
provide a first chunk to compress with size `< MINMATCH`.
The chunk is not compressed but becomes a dictionary.
No hash was generated / stored in the hash table,
but the chunk is accessible as default position 0 points to dictStart,
and position 0 is still within `MAX_DISTANCE`.
Then, next attempt to read 32-bits from position 0 fails.
The issue would have been mitigated by starting from index 64 KB,
effectively eliminating position 0 as too far away.
Another possible fix is to eliminate such "dictionary" from history since it's too small.
Which is what this …

Fix frametest error

---

lib/lz4hc.c

Finally found a way to integrate
a new speed optimization for LZ4 optimal parser, named Chain Swap,
into the generic match finder,
thus supporting all search scenarios (extDict and CDict).
Results are pretty good : 
benchmark on `entropy`, `gcc-7`, highest compression mode `-12` :
| Name | -12 (dev) | -12 (this patch) | Improvement |
| --- | --- | --- | --- |
| calgary.tar | 6.2 MB/s | 16.2 MB/s | +160 % |
| enwik7 | 15.6 MB/s | 18.7 MB/s | +20 % |
| silesia.tar | 5.8 MB/s | 13.8 MB/s | +140 % |
Performance improvement vary depending on file, but good news is,
slowest files see the biggest improvements.
Benefits are mostly present at level 12.
Level 11 still see some benefit, but much lower, in the ~20% range.
Level 10 see a strange reversal, with same speed or slightly slower, but better …

Speed optimization for optimal parser

---

.travis.yml
Makefile
circle.yml
lib/lz4.c
lib/lz4hc.h
tests/fullbench.c

Oops.
Also adds a test that builds the library with a C compiler and then builds the tests (standing in for library users) on top with a C++ compiler to make sure everything links correctly.

Add `extern "C"` Guard Around Experimental HC Declarations

---

lib/Makefile

When cross-compiling for example from Darwin to Linux it might be
useful to override uname output to force Linux and create Linux
libraries instead of Darwin libraries.

allow to override uname when cross-compiling

---

tests/fuzzer.c

Fix compile error of fuzzer.c on AIX 32 bit builds.  On AIX 32 bit, sys/mman.h must be included after platform.h else we get errors shown in the attachment, likely caused by bugs in AIX header files.
AIX 64 bit builds also run clean with this change.
[lz4_aix_32bit.txt](https://github.com/lz4/lz4/files/2063868/lz4_aix_32bit.txt)

Aix 32bit fuzzer

---

contrib/cmake_unofficial/CMakeLists.txt

Provide a CMake option to not build legacy command line support in lz4c.
CMake FYI: @nemequ

Add CMake option to not build legacy lz4c program

---

lib/lz4hc.c
programs/bench.c
tests/.gitignore
tests/Makefile
tests/fuzzer.c
tests/roundTripTest.c

This patch does 2 things : 
- fixes bug #560 
- introduces a new tool, `tests/roundTripTest`, designed to catch corruption bugs in collaboration with `afl`.
We already have round trip tests, inside `fuzzer` and `frametest`.
However, these test generate compressible random data, hence do not have a capability to "search" good candidates through code instrumentation as `afl` does. For issues like #560, the amount of conditions to gather is so large that finding it by testing random things is astronomically improbable.
The intention is to use `roundTripTest` with `afl` to help find bugs equivalent to #560.
Unfortunately, even `afl` cannot find #560 just by itself.
#560 can only be triggered by "large enough" files (> 64 KB), which is out of reasonable search zone for `afl`.
Nonetheless, …

Round trip test for #560

---

examples/frameCompress.c

The decompression was failing as the srcEnd pointer in
decompress_file_internal was wrongly computed beyond
the end of the memory block.
We need to account for the fact that the header ("info")
was already read in the calling function ("alreadyConsumed").

Fix bug in frame decompress example

---

examples/frameCompress.c
lib/lz4frame.h

to simplify initialization of `lz4frame.h` structures.
Partially in response to #546.

Introduced constants LZ4F_INIT_*

---

Makefile
doc/lz4_manual.html
doc/lz4frame_manual.html
examples/frameCompress.c
lib/lz4frame.c
lib/lz4frame.h
lib/lz4hc.c

as detected in #485 by @JoachimSchneider.
Refactored the `c_standards` tests
so that these issues get automatically detected in CI tests.

avoid final trailing comma for enum lists

---

doc/lz4_manual.html
doc/lz4frame_manual.html
lib/README.md
lib/lz4.h

Functions declared behind protection macro `LZ4_STATIC_LINKING_ONLY`
are now _not_ published in dll by default.
This can be reversed via opt-in build macro `LZ4_PUBLISH_STATIC_FUNCTIONS`,
mirroring what's currently happening in `lz4frame.h`.
Used this opportunity to update a bunch of api comments within `lz4.h`.

unpublish static-only functions

---

doc/lz4_manual.html
lib/lz4.c
lib/lz4.h
lib/lz4hc.h

This answers https://github.com/lz4/lz4/issues/485,
making it possible for `lz4` to compile on systems with 128-bit pointers.
I've taken the less disruptive approach to only increase size constants when pointers are detected as 128-bits (defined as `sizeof(void*)==16`). This way, the API remains unchanged for existing 32-bit and 64-bit systems.
Other possibilities involved increasing the size for all ABIs, or to get rid of the size and force usage of the `struct` definition. They were less preferred, due to risks of potentially breaking some unidentified user applications.
_Note_ : I'm unfortunately unable to test this change, as I don't have any AS400 emulator around (nor cross-compiler), so I've trusted values provided by @JoachimSchneider . Finding a way to test compilation on such …

Support for 128bit pointers like AS400

---

lib/lz4frame.c

when `LZ4F_decompress()` decodes an uncompressed block,
it may provide an incorrect hint for next block
when frame checksum is enabled and block checksum is not.
Impact is low : the hint is just an hint,
so the decoder still works correctly, whatever the amount of input provided.
But the assumption that each call to `LZ4F_decompress()`
would generate just one complete block when input size hint was respected
end up being false with this error.

fixed improper hint

---

lib/lz4frame.c
lib/lz4frame.h
tests/frametest.c

as mentioned by @raggy in #589.
The fix proposed here is slightly different, but achieves the same goal.
More importantly, it is backed by a test tool which checks this case during CI tests.

fix LZ4F_compressEnd()

---

lib/lz4hc.c
lib/lz4hc.h
tests/fuzzer.c

With this change an HC compression function in case of failure will update the stream's state to have "dirty context". It is safe now to pass such a stream into `LZ4_resetStreamHC_fast()` function, because it will detect "dirty context" internally and fall back to full reset then.
What was changed:
* renamed `favorDecSpeed` field to `flags`, first 11 bits are not used currently, 12th bit is used to indicate if context is dirty, last 4 bits are reserved for favor kinds;
* updated `LZ4HC_compress_generic_internal()` function to set "dirty context" flag (`lz4hc.c` has complex hierarchy of function calls, therefore refer to the picture);
* updated `LZ4_resetStreamHC_fast()` to detect "dirty context" case;
* updated the tests.

Adding information about dirty context for _HC_ family of functions

---

lib/Makefile

This allow cross-compilation for Windows on Linux

Use / instead of \ when accessing files in the dll subdirectory.

---

Makefile
lib/Makefile
lib/README.md
programs/Makefile

- When cross-compiling (64 bits cross compiler) : 
```make install PREFIX=$HOME/lz4_test BUILD_STATIC=no CC=x86_64-w64-mingw32-gcc DLLTOOL=x86_64-w64-mingw32-dlltool OS=Windows_NT```
```find /home/vtorri/lz4_test``` gives : 
/home/vtorri/lz4_test/
/home/vtorri/lz4_test/lib
/home/vtorri/lz4_test/lib/liblz4.lib
/home/vtorri/lz4_test/lib/pkgconfig
/home/vtorri/lz4_test/lib/pkgconfig/liblz4.pc
/home/vtorri/lz4_test/share
/home/vtorri/lz4_test/share/man
/home/vtorri/lz4_test/share/man/man1
/home/vtorri/lz4_test/share/man/man1/lz4c.1
/home/vtorri/lz4_test/share/man/man1/lz4cat.1
/home/vtorri/lz4_test/share/man/man1/lz4.1
/home/vtorri/lz4_test/share/man/man1/unlz4.1
/home/vtorri/lz4_test/bin
/home/vtorri/lz4_test/bin/unlz4.exe
/home/vtorri/lz4_test/bin/liblz4-1.dll …

Allow installation of lz4 for Windows (MSYS2 or when cross-compiling)

---

tests/frametest.c
tests/fuzzer.c

Those warnings:
```c
../tests/fuzzer.c:681:116: error: format specifies type 'void *' but the argument has type 'const char *' [-Werror,-Wformat-pedantic]
DISPLAYLEVEL(5, " compress %i bytes from buffer(%p) into dst(%p) using dict(%p) of size %i \n", blockSize, block, decodedBuffer, dict, dictSize);
~~                                                         ^~~~~
%s
../tests/fuzzer.c: In function ‘FUZ_test’:
../tests/fuzzer.c:511:30: error: overflow in implicit constant conversion [-Werror=overflow]
{   char const tmp = 0xFF;
^~~~
../tests/fuzzer.c:521:20: error: overflow in implicit constant conversion [-Werror=overflow]
*tmp = 0xEE;
^~~~
```
Those warnings would be treated as errors in release build or when build tests in meson.

Fix clang warning

---

lib/lz4frame.c
lib/lz4frame.h
tests/frametest.c

Publish the `LZ4_getBlockSize` function to the experimental section of the API. 
This resolves #608

Make LZ4F_getBlockSize public and public in experimental section

---

lib/lz4hc.c

Every 0xff byte in the compressed block corresponds to a length of 255 (not 256) in the input data. For long repeating sequences, using (length >> 8) may generate bad compressed blocks.

 lz4hc.c: change (length >> 8) to (length / 255)

---

programs/lz4cli.c
programs/lz4io.c
programs/lz4io.h
tests/Makefile

This PR resolves issues surrounding pass-through mode with lz4. It does so by adding an additional flag to to signify pass-through mode in `LZ4IO`, we then use this when selecting the decoder.
Resolves #601

Fix pass-through mode

---

programs/lz4cli.c
programs/lz4io.c
programs/lz4io.h

Previously, the various preferences for the IO module were tracked via a number of global variables. This PR, gets rid of the global variables related to the IO and compression, and packages them up in a struct that is passed around throughout the code.

Remove a bunch of global variables that tracked settings for the IO module

---

lib/lz4.c

Clang doesn't support the GCC optimize attribute.

Eliminate optimize attribute warning with clang on PPC64LE

---

visual/VS2017/lz4.sln

Build on VS2017 fails due to the presence of redundant lz4 project inherited from 2010. Simple remove fixes the build.

Build fixed by removing unavailable project

---

lib/lz4.c

The current decompress_generic code suffers from many blocked loads, originally mentioned in issue #411. This patchset attemps to fix that issue.  Also similar issues mentioned in pull #470 , issue #126, and probably others.
The heart of the issue is that LZ4_wildCopy does a copy by 8 bytes at a time, leading to lots of work happening side-by-side.   The farther away we can move these copies by extending the copy width, the faster things seem to go.  Increasing the copy width to as wide as 32 bytes results in overall decompression speed improvement of around ~10% a xeon, ~20% on a modern AMD.
The primary code challenge then is that we have only 8 bytes of WILDCOPYLENGTH, when we'd really like far larger.  So we end up duplicating most of the decode loop, to add a fastpath for a larger …

Optimize decompress generic

---

doc/lz4_manual.html
doc/lz4frame_manual.html
examples/compress_functions.c
lib/README.md
lib/lz4.h
lib/lz4hc.h
tests/fullbench.c
tests/fuzzer.c

They are no longer faster than `_safe()` 
(actually, they can even be slower)
but open the door to security issues, since they are not protected against malicious input.

Deprecated LZ4_decompres_fast*() functions

---

Makefile
doc/lz4_manual.html
examples/blockStreaming_doubleBuffer.c
examples/dictionaryRandomAccess.c
lib/lz4.c
lib/lz4.h
lib/lz4frame.c
lib/lz4hc.c
lib/lz4hc.h
tests/Makefile
tests/checkFrame.c
tests/frametest.c
tests/fullbench.c
tests/fuzzer.c

Following discussion on LZ4 v1.9.0 API evolution,
here is a proposal pushing `LZ4_resetStream*fast()` into "stable" category.
As a consequence, it triggers a number of additional decisions related to API consistency.
- `LZ4_resetStream*_fast()` is now the recommended method to start a new stream of blocks, since it's faster.
- But it cannot completely replace `LZ4_resetStream*()` for uninitialized objects
- Since it's hard to explain the difference between `reset` and `reset_fast` in term of "one is an initializer, the other is the recommended reset", I created `LZ4_initStream*()` for the sole purpose of initializing `LZ4_stream*_t` objects allocated by the user (typically on stack) and which may contain arbitrary garbage values.
The main issue in this patch is : what is the exact scope …

LZ4_resetStream*_fast()

---

doc/lz4_manual.html
doc/lz4frame_manual.html
lib/README.md
lib/lz4.c
lib/lz4hc.c
programs/Makefile

make it possible to generate LZ4-compressed block
with a controlled maximum offset (necessarily <= 65535).
This could be useful for compatibility with decoders
using a very limited memory budget (<64 KB).
Answer #154

introduce LZ4_DISTANCE_MAX build macro

---

programs/lz4.1
programs/lz4.1.md
programs/lz4cli.c
tests/Makefile

This is the reverse of `-BD`, and the current default.
This command can be useful to reverse a previous `-BD` command.
It may become more important in the future 
if `lz4` switches to generating dependent blocks by default.

added command -BI for "Independent Blocks"

---

.gitignore
programs/lz4cli.c
programs/lz4io.c
programs/lz4io.h
tests/Makefile

fix #641
It's now possible to compress multiple files into `stdout`, using commands `-m -c`.
Previously, `-m` was hardwired to generate one `.lz4` file per source file, thus ignoring `-c`.
The decompression side works too : `-d -m -c` decompress multiple files into `stdout`.
Works with shortcuts `unlz4` and `lz4cat`.
But this patch only adds tests for this use case.
`lz4` already supported it.

Fix combination -m -c

---

lib/lz4.c
lib/lz4.h
lib/lz4hc.c
tests/fuzzer.c

Since the patch introducing automatic `dirty` context detection, 
`lz4frame` efficiency is impacted
when using linked blocks  : 
as soon as one block is "not compressible", it also tags the context as `dirty`, and then refuses to compress future blocks, which are then output uncompressed by `lz4frame`, destroying the compression ratio.
This happens on `silesia.tar` by using command line parameter `-B4D`.
This patch solves this situation, by no longer tagging the context as `dirty` after a failed block compression. The reason is, all indexes are still correct, the context is still fully usable, can compress more blocks, and can receive a fast reset, so it's not actually `dirty`, aka "unusable until fully `initialized` again".

Fix lz4frame inefficiency

---

lib/lz4.c
lib/lz4.h
programs/bench.c
tests/checkFrame.c
tests/frametest.c
tests/fuzzer.c

fix #676,
also deprecated `LZ4_decompress_fast()`,
which now generates deprecation warnings by default.
Note also that `LZ4_decompress_fast()` is now slower than `LZ4_decompress_safe()`,
removing any incentive to use it in place of the more secure variant.

Fix out-of-bound read in LZ4_decompress_fast()

---

lib/lz4.c
lib/lz4hc.c
tests/fuzzer.c

and add relevant test in `fuzzer`
fix #681

fixed read-after input in LZ4_decompress_safe()

---

.travis.yml
programs/lz4.1.md
programs/lz4cli.c
tests/Makefile

Fix #675 
`lz4` defaults to `stdout` for single-file compression whenever it detects that `stdout` is not the CONsole.
This behavior is problematic, because some environments start `lz4` without identifying `stdout` as console.
This leads to a change of behavior for a same line of script.
This behavior has been preserved so far for compatibility with existing ecosystem.
A more sensible policy could be to default to `stdout` only when input is `stdin`.
But there is a risk of breaking existing scripts.
Soft change for the time being : keep the behavior as it is, but print a warning message,
to invite users to prefer `-c` to explicitly select `stdout`.
Also : updated tests in Makefile to explicitly select `stdout` with `-c`.

cli: warning for stdout as default output

---

Makefile.inc
lib/Makefile
lib/liblz4-dll.rc.in
programs/Makefile
programs/lz4-exe.rc.in
tests/Makefile

Moved a few other tests to Makefiles.inc.  Other things might need to go there.
Made a test for symlink appropriateness.  Windows can NOT handle them the same way Unix-like operating systems do (if at all).  This is mostly the same as the Visual C projects.
embed version info into .dll and .exes that are redistributed.

More build imrpvements

---

lib/lz4frame.c

This results in a slightly increased dstCapacity when preferencesPtr is null.

Include block checksum in worst case scenario calculation of dstCapacity

---

lib/lz4.c

Pull request #645 has introduced the build macro LZ4_FAST_DEC_LOOP which by default enables an optimization only for x86/x64.
I propose to enable this optimization for aarch64 as well. Here are the benchmark results for this pull request running on a1.4xlarge AWS EC2 instance. The final percent is how much faster this patchset is vs. the current dev branch.
```
./lzbench -elz4 silesia/*
lz4 1.8.3                 148 MB/s  1335 MB/s     6428742  63.07 silesia/dickens    
lz4 1.8.3                 147 MB/s  1319 MB/s     6428742  63.07 silesia/dickens    -1%
lz4 1.8.3                 229 MB/s  1503 MB/s    26435667  51.61 silesia/mozilla    
lz4 1.8.3                 229 MB/s  1630 MB/s    26435667  51.61 silesia/mozilla    8%
lz4 1.8.3                 216 MB/s  1350 MB/s     5440937  54.57 …
```

enable LZ4_FAST_DEC_LOOP build macro on aarch64 by default

---

lib/lz4frame.c
lib/lz4frame.h
programs/lz4cli.c
programs/lz4io.c
programs/lz4io.h
tests/Makefile
tests/test-lz4-list.py

```
» ~/lz4/tests ## list * make listTest
python3 test-lz4-list.py
2019/05/10 16:52:59 - Generating /tmp/test_list_5M
2019/05/10 16:52:59 - > ./datagen -g5M > /tmp/test_list_5M
2019/05/10 16:52:59 - > /home/gabriel/lz4/tests/../lz4 --content-size /tmp/test_list_5M /tmp/test_list_5M-lz4f-1f--content-size.lz4
2019/05/10 16:52:59 - > /home/gabriel/lz4/tests/../lz4 -BI /tmp/test_list_5M /tmp/test_list_5M-lz4f-1f-BI.lz4
2019/05/10 16:52:59 - > /home/gabriel/lz4/tests/../lz4 -BD /tmp/test_list_5M /tmp/test_list_5M-lz4f-1f-BD.lz4
2019/05/10 16:52:59 - > /home/gabriel/lz4/tests/../lz4 -BX /tmp/test_list_5M /tmp/test_list_5M-lz4f-1f-BX.lz4
2019/05/10 16:52:59 - > /home/gabriel/lz4/tests/../lz4 --no-frame-crc /tmp/test_list_5M /tmp/test_list_5M-lz4f-1f--no-frame-crc.lz4
2019/05/10 16:52:59 - > …
```

Add multiframe report to --list command

---

.circleci/config.yml
Makefile
tests/Makefile

- only play `listTest` within `make test`, instead of `make all` which is limited to build
- update `clangtest`, so that it's possible to disable O3 optimization, for faster processing

updated tests for CircleCI

---

lib/lz4frame.c

I noticed a bug, that forces lz4frame decompression to use a temporary source buffer in the case when size hint is respected, but dst buffer is not fully exhausted.
After next block header is read, the `dstage_getCBlock` state expects input based on  dctx->tmpInTarget, but remaining buffer size will always be 0, after reading a header, if src buf had been of a hint size, so it transitions to `dstage_storeCBlock` state. So, when one optimizes their code to always provide the src buffer of the hinted size, all compressed blocks will always hit the temporary buffer, unless they're lucky having destination buffer exhausted.
This has a very notable speed impact on some embedded hardware, where only a limited amount of fast memory is available and you never want to hit tmp buffers.

Fix src temporary buffer use in lz4frame

---

lib/lz4.c

When I did FAST_DEC_LOOP performance test, I found the
offset check is much more than v1.8.3
You will see the condition check difference via lzbench with dickens test case.
v1.8.3 34959
v.1.9.x 1055885
After investigate the code, we could see the difference.
v.1.8.3 SKIP the condition check if
if condition is true in:
https://github.com/lz4/lz4/blob/v1.8.3/lib/lz4.c#L1463
AND below condition is true
https://github.com/lz4/lz4/blob/v1.8.3/lib/lz4.c#L1478\
The offset check should be invoked.
v1.9.3
The offset check code will be invoked in every loop which lead to downgrade.
So the fix would be move this check to specific condition
to avoid useless condition check.
After this change, the call number is same as v1.8.3

FAST_DEC_LOOP: move offset check in specific condition.

---

tests/fullbench.c

This emulates a streaming scenario,
where the caller follows rigorously the srcSize hints
provided as return value of `LZ4F_decompress()`.
This is useful to show the issue in #714,
where data is uselessly copied into an internal tmp buffer first,
resulting in a loss of performance.
Note that, even with #714, performance of "followHint" scenario is still inferior to "single pass" scenario,
where all input data is provided in a single invocation to `LZ4F_decompress()`.

fullbench: added test scenario LZ4F_decompress_followHint

---

.circleci/config.yml
.circleci/images/primary/Dockerfile

Instead of installing dependencies before test, use custom Docker Image with pre-installed dependencies.

CircleCI : use custom Docker Image with pre-installed dependencies

---

.travis.yml
examples/HCStreaming_ringBuffer.c
tests/fullbench.c
tests/fuzzer.c

Upgraded `tests/fuzzer.c` so that it can detect issues like #738. 
Best used with Address Sanitizer (`asan`), so that any potential out-of-bound reads get immediately caught.
The test is automatically run on TravisCI.
In a version without fix #740, [the `asan` test fails as expected](https://travis-ci.org/lz4/lz4/jobs/552045183). [`valgrind`](https://travis-ci.org/lz4/lz4/jobs/552045187) is another test that fails.
After applying #740 fix (this PR), all tests pass.

New fuzzer test for #738

---

.travis.yml
contrib/meson/README.md
contrib/meson/contrib/gen_manual/meson.build
contrib/meson/meson.build
contrib/meson/meson_options.txt

Meson now reserves `build_` prefix options.

meson: Fix deprecated warnings on build options

---

doc/lz4_manual.html
doc/lz4frame_manual.html
lib/lz4.h
programs/lz4.1
programs/lz4io.c

to reduce chances that future bug(s) using `dev` branch report `v1.9.1` as the failing version.

bumped version number to v1.9.2

---

.circleci/config.yml

Ideally, we want to make CircleCI a "fast" test environment, with short feedback loop (~5mn).
We are still far from this goal.
This patch starts this process by removing "long" tasks which are non-essential and redundant with travisCI. It reduces tests duration from ~45mn to ~19mn.
It also acknowledges that parallelism is broken.
The script will have to be more heavily updated to support parallelism.

CircleCI : reduced test duration

---

.travis.yml
lib/README.md
lib/lz4.c
tests/Makefile
tests/frametest.c

Follow up from #753 : 
It's now possible to select a custom `LZ4_DISTANCE_MAX` at compile time,
provided it's `<= 65535`.
However, in some cases (compression using `byU16` mode),
the custom distance wasn't always respected,
as offsets used to be implied as "in range" in this mode, and therefore wasn't checked.
Added a distance check for this case.
The check is only active when `LZ4_DISTANCE_MAX < 65535`.
Otherwise, it's a no-op (default).
Also : added a new TravisCI test which ensures that
custom `LZ4_DISTANCE_MAX` compiles and compresses correctly,
relying on `assert()` to find outsized offsets.

ensure conformance with custom LZ4_DISTANCE_MAX

---

lib/lz4.c

* Allow 2 extra match code bytes (line 1033).
* Fix a rare data corruption bug in LZ4_compress_destSize
When we had to shorten the match to fit in the output buffer, and the new match is before the `ip` where we found the match because of the "catch up" there will be positions in the table that are beyond the new `ip`. We must zero those positions so we don't corrupt the hash table.
Credit to OSS-Fuzz

[LZ4_compress_destSize + multi-blocks streaming] Fix rare data corruption bug

---

lib/lz4.c
lib/lz4frame.c
lib/lz4hc.c
ossfuzz/Makefile
ossfuzz/compress_frame_fuzzer.c
ossfuzz/compress_hc_fuzzer.c
ossfuzz/decompress_frame_fuzzer.c
ossfuzz/fuzz_helpers.h
ossfuzz/lz4_helpers.c
ossfuzz/lz4_helpers.h
ossfuzz/ossfuzz.sh
ossfuzz/round_trip_frame_fuzzer.c
ossfuzz/round_trip_hc_fuzzer.c
ossfuzz/round_trip_stream_fuzzer.c
ossfuzz/travisoss.sh

LZ4Frame changes:
* Skip magic and checksums in fuzzing mode (when `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` is defined)
Fuzzers:
* Round trip fuzzer
* Compress fuzzer
* Decompress fuzzer
This PR is based on top of the stream-fuzz PR and Felix's PR.

[fuzz] Add LZ4 frame fuzzers

---

lib/lz4.c
lib/lz4hc.c
ossfuzz/Makefile
ossfuzz/compress_hc_fuzzer.c
ossfuzz/fuzz_helpers.h
ossfuzz/ossfuzz.sh
ossfuzz/round_trip_hc_fuzzer.c
ossfuzz/round_trip_stream_fuzzer.c
ossfuzz/travisoss.sh

Fuzzers
* Streaming compression with prefix
* Streaming compression with extDict
* Streaming compression with loaded dictionary
* Streaming compression with attached dictionary
* Streaming compression with all of the above in HC mode
* LZ4HC round trip fuzzer
* LZ4HC compress fuzzer
Fixes:
* Fixed `LZ4_attach_dictionary()` with an empty dictionary. It would find matches **beyond** the end of the dictionary causing asserts to fail. CC @felixhandte.

[fuzz] Add streaming round trip fuzzer

---

lib/lz4hc.c

This diff fixes an issue in which we failed to clear the `dictCtx` in HC
compression. The `dictCtx` is not supposed to be used when an `extDict` is
present: matches found in the `dictCtx` do not account for the presence of an
`extDict` segment, and their offsets are therefore miscalculated when one is
present. This can lead to data corruption.
This diff clears the `dictCtx` whenever setting an `extDict`.
This issue was uncovered by @terrelln's fuzzing work.

Fix Data Corruption Bug when Streaming with an Attached Dict in HC Mode

---

lib/lz4.c

The next match is looking at the current ip, not the next ip,
so it needs to be cleared as well.
Credit to OSS-Fuzz

[LZ4_compress_destSize] Fix off-by-one error in fix

---

lib/lz4frame.c

We don't verify checksums when fuzzing is enabled, so mark them as explicitly unused.

[lz4frame] Fix unused variable warnings in fuzzing mode

---

programs/lz4.1
programs/lz4.1.md
programs/lz4cli.c

This option exists in **gzip(1)**, **bzip2(1)**, **lzma(1)** and similar commands.

Add option '--best' to lz4(1)

---

lib/lz4hc.c

* Add an acceleration parameter to chain swapping to speed it up in the case of long unfruitful matches. This is approximately neutral for the common case, but speeds up long matches considerably. This showed up as slow units in my fuzzing (1 MB took 50 seconds with ASAN or 12 seconds in an optimized build).
* Fix a typo bug in the forward extension `s/ip/matchPtr`.
* In the pattern detection code, make sure we never set `matchCandidateIdx` or `matchIndex` to within 3 bytes of the end of the dictionary using `LZ4HC_protectDictEnd()`. This could cause data corruption and/or a read out of bounds.
* Extend the match backwards if it hits `lowPrefixPtr`. This was the OSS-Fuzz slow unit cause. Credit to OSS-Fuzz.
The compression ratio is the same for every file in silesia, calgary, and enwik7. …

[lz4hc] Further improve pattern detection and chain swapping

---

lib/lz4.c
tests/.gitignore

Ensure target buffer get overwritten with 0 when `offset==0` is specified in the compressed block.
This fix seems, on average, slightly performance detrimental, in the vicinity of <1% loss. Note that I can't access my benchmark platform at the moment, so I'm using my laptop, and performance variations between measurements is high on this platform, so measured differences could be noise.
| name | `dev` | `offset0` |
| --- | --- | --- |
| silesia | 4263 MB/s | 4250 MB/s |
| calgary | 4369 MB/s | 4358 MB/s |
| enwik8 | 3939 MB/s | 3946 MB/s |

silence msan warning when offset==0

---

lib/lz4.c

When using an empty dictionary, we bail out of loading or attaching it in
ways that leave the working context in potentially slightly different states.
In particular, in some paths, we will cause the currentOffset to be non-zero,
while in others we would allow it to remain 0.
This difference in behavior is perfectly harmless, but in some situations, it
can produce slight differences in the compressed output. For sanity's sake,
we currently try to maintain a strict correspondence between the behavior of
the dict attachment and the dict loading paths. This patch restores them to
behaving identically.
This shouldn't have any negative side-effects, as far as I can tell. When
writing the dict attachment code, I tried to preserve zeroed currentOffsets
when possible, since they benchmarked as …

Make Attaching an Empty Dict Behave the Same as Using it Directly

---

lib/lz4.c

PR#756 fixed the data corruption bug, but didn't clear `ip`. PR#760
fixed that off-by-one error, but missed the case where `ip == filledIp`,
which is harder for the fuzzers to find (it took 20 days not 1 day).
Verified this fixed the issue reported by OSS-Fuzz.
Credit to OSS-Fuzz.

[LZ4_compress_destSize] Fix off-by-one error

---

ossfuzz/Makefile
ossfuzz/compress_frame_fuzzer.c
ossfuzz/compress_fuzzer.c
ossfuzz/compress_hc_fuzzer.c
ossfuzz/decompress_frame_fuzzer.c
ossfuzz/decompress_fuzzer.c
ossfuzz/fuzz_data_producer.c
ossfuzz/fuzz_data_producer.h
ossfuzz/round_trip_hc_fuzzer.c

Consuming bytes from the end of data instead of from the front to prevent "all-in-one" decisions.

Adding fuzz data producer for uint32 and using in decompress_fuzzer

---

programs/platform.h
programs/util.h

utime was deprecated in POSIX 2008.

util.h: Remove deprecated utime for non-Windows
